#  Stylesheets
Rails.application.config.assets.precompile += [
    'colorpicker.css',
    'font.css',
    'form.css',
    'general.css',
    'ie.css',
    'ie6.css',
    'ie7.css',
    'iwing.css',
    'jquery.autocomplete.css',
    'jquery.rating.css',
    'jquery.ui.potato.menu.css',
    'layout.css',
    'prayer_pledge.css',
    'print.css',
    'public_info.css',
    'reset.css',
    'screen.css',
    'site.css',
    'style.css',
    'tiny_mce.css',
    'typography.css',
    'blue/style.css',
    'calendar_date_select/blue.css',
    'calendar_date_select/default.css',
    'calendar_date_select/plain.css',
    'calendar_date_select/red.css',
    'calendar_date_select/silver.css',
    'fsn/jquery-ui-1.7.1.custom.css',
    'master/font.css',
    'master/form.css',
    'master/general.css',
    'master/ie.css',
    'master/layout.css',
    'master/print.css',
    'master/reset.css',
    'master/screen.css',
    'master/style.css',
    'master/typography.css'
      ]

# Javascript
Rails.application.config.assets.precompile += [
    'audio-player.js',
    'prototype.js',
    'jquery-1.3.2.min.js',
    'jquery.qtip-1.0.0.min.js',
    'jquery-ui-1.7.1.custom.min.js',
    'jquery.tablesorter.min.js',
    'jquery.MetaData.js',
    'jquery.rating.js',
    'jquery.validate.min.js',
    'colorpicker.js',
    'iColorPicker.js',
    'jquery.corner.js',
    'jquery.bgiframe.js',
    'jquery.ajaxQueue.js',
    'jquery.autocomplete.min.js',
    'player/swfobject.js',
    'wforms_core.js',
    'wforms_sync.js',
    'wforms_validation.js',
    'wforms_switch.js',
    'wforms_repeat_rails.js',
    'jquery.tools.min.js',
    'jquery.ui.potato.menu.js',
    'swfobject.js',
    'jquery.jtree.1.0.min.js',
    'jquery.jtree.1.0.js',
    'tiny_mce/tiny_mce.js'
      ]

# Images
Rails.application.config.assets.precompile += [
    'discussion_ico.gif',
    'discussion_ico_h.gif'
      ]