development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: tcpj_pilot
  pool: 5
  username: root
  password:
  host: localhost
 
test:
  development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: tcpj_pilot_test
  pool: 5
  username: root
  password: 
  host: localhost

production:
  development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: escent_ifa_pilot
  pool: 5
  username: tcpj
  password: floptarts
  host: localhost
  socket: /var/lib/mysql/mysql.sock
