development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: tcpj_upgrade
  pool: 5
  username: root
  password:
  host: localhost
 
test:
  development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: tcpj_upgrade_test
  pool: 5
  username: root
  password: 
  host: localhost

production:
  development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: tcpj_upgrade_prod
  pool: 5
  username: tcpj
  password: floptarts
  host: localhost
  socket: /var/lib/mysql/mysql.sock
